### Testar cadastro de livro
POST http://localhost:8080/api/livros
Content-Type: application/json

{
  "titulo": "O Guia do Mochileiro das Galáxias",
  "autor": "Douglas Adams",
  "genero": "Ficção Científica",
  "descricao": "Uma série de comédia de ficção científica criada por Douglas Adams.",
  "preco": 35.90
}
